apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    subpath-test-pvc: "data-set-1/v1/000/1;data-set-1/v3/train/3"
    union-test-pvc: "true"
    sync-test-pvc: "true"
spec:
  containers:
    - args:
        - -c
        - sleep 3600
      command:
        - /bin/sh
      image: registry.cn-shenzhen.aliyuncs.com/fscomfs/mount:v1.1.0
      name: app
      volumeMounts:
        - mountPath: /home/data
          name: data
          mountPropagation: HostToContainer
      resources:
        requests:
          cpu: 10m
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pvc
