apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    test-pvc-subpath: "/data/www;/data/qqq"
    union-test-pvc: "true"
spec:
  containers:
    - args:
        - -c
        - while true; do echo $(date -u) >> /data/out.txt; sleep 5; done
      command:
        - /bin/sh
      image: 192.168.1.76:8099/evtrain/cvmart-daemon:v1.0
      name: app
      volumeMounts:
        - mountPath: /data
          name: data
      resources:
        requests:
          cpu: 10m
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pvc