apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    test-pvc-subpath: "/data/www;/data/qqq"
    union-test-pvc: "true"
spec:
  containers:
    - args:
        - -c
        - sleep 3600
      command:
        - /bin/sh
      image: juicedata/juicefs-csi-driver:nightly
      name: app
      volumeMounts:
        - mountPath: /home/data
          name: data
          mountPropagation: HostToContainer
      resources:
        requests:
          cpu: 10m
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pvc
