apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    subpath-cvmart-data-set-pvc: "data-set-1/v1/000/1;data-set-1/v3/train/3"
    union-cvmart-data-set-pvc: "true"
    sync-cvmart-data-set-pvc: "false"
spec:
  containers:
    - args:
        - -c
        - sleep 3600
      command:
        - /bin/sh
      image: 192.168.1.76:8099/evtrain/cvmart-daemon:v1.0
      name: app
      volumeMounts:
        - mountPath: /home/data
          name: data
          mountPropagation: HostToContainer
      resources:
        requests:
          cpu: 10m
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: cvmart-data-set-pvc
